Feature/blaba
feitzi/AdvancedSecuritySample pull request #10
Opened 2022-07-19 14:41 UTC by feitzi

2022-07-19 14:41 UTC, bst-wd commented
test

2022-07-19 14:47 UTC, bst-wd requested changes
Bitte nochmal dr[ber nachdenken ob du wirklich leading sein kannst

2022-07-19 14:47 UTC, bst-wd commented on README.md
> +# Danger
ist das vom Christoph? 😬

2022-07-19 14:47 UTC, bst-wd commented on README.md
>  ~~~
das ist m[ll

2022-07-19 14:54 UTC, feitzi reviewed
gjh

2022-07-19 14:54 UTC, feitzi commented on README.md
> +Sample 123456
Sample

2022-07-19 14:57 UTC, merged

2022-07-21 12:42 UTC, feitzi reviewed
Bitte schau dir das an!

2022-07-21 12:42 UTC, feitzi commented on README.md
>  //sample
Weshalb?

2022-07-21 12:42 UTC, feitzi commented on README.md
> +dgdfg
kxbkmvnbdsv